esphome:
  name: "Vindriknitning"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret Vindriknitning.otapasswd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01Dht Fallback Hotspot"
    password: !secret Vindriknitning.FAPpasswd

captive_portal:
uart:
  rx_pin: GPIO00
  baud_rate: 9600
  
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO2
    temperature:
      name: "Vindriknitning Temperature"
      force_update: true
    humidity:
      name: "Vindriknitning Humidity"
    update_interval: 60s
  - platform: pm1006
    pm_2_5:
      name: "Vindriknitning PM2.5"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 50
            send_every: 10
            send_first_at: 10